<?php
	include('accesscheck.php');
	$appno = stripslashes($_GET['appno']);
	$testcenter = stripslashes($_GET['center']);
	$timingslot="10:00 A.M.";
	$date_of_exam = "28-05-2016";
		require('../authentication/fpdf/fpdf.php');
		$pdf = new FPDF('P','mm','A4');
		if ($stmt = $mysqli->prepare("SELECT * FROM gatCenterSlots where centerId = ?")) { 
			$stmt->bind_param('s', $testcenter); 
			$stmt->execute();
			$stmt->store_result();
			$stmt->bind_result($centerName,$centerAddress,$contactPerson,$contactNumber,$dateOfTest,$slot1,$slot2,$slot3); 
			$stmt->fetch();
		}		
		$path='../authentication/halltickets/'.$centerName.'/';
		$id=$appno.'.pdf';
		$pdffilename=$path.$id;	
		$pdf->SetAuthor("MSIT");
		$pdf->SetTitle("MSIT");
		$pdf->SetCreator("Hallticeket Generator");
		$pdf->SetSubject("Halltickets 2016");
		$pdf->AddPage();	
		$pdf->SetFont('times','B',20);
		$pdf->SetXY(18,15);
		$pdf->Cell('','5','Consortium of Institutions of Higher Learning  ','','','C');		
		$pdf->Cell('','3','');
		$pdf->SetXY(15,25);
		$pdf->SetFont('times','B',10);
		$pdf->Cell('','','IIIT Campus, Gachibowli, Hyderabad - 32, Phone: 040-23001970,Mobile: 7799834583, 7799834585','','','C');
		$pdf->Cell('','3','');
		$pdf->Image('../authentication/images/line.jpg','25','30','162');
		$pdf->Cell('','3','');
		$pdf->Image('../authentication/images/msit.jpg','25','35','35');
		$pdf->SetFont('times','B',14);			
		$pdf->SetXY(45,38);
		$pdf->Cell('','','Master of Science in Information Technology','','','C');
		$pdf->Cell('','3','');
		$pdf->SetXY(45,44);
		$pdf->Cell('','','Entrance Test 2016','','','C');			
		$pdf->SetFont('times','B',16);
		$pdf->Cell('','3','');
		$pdf->SetXY(45,52);
		$pdf->Cell('','','HALLTICKET','','','C');
		$pdf->SetFont('times','B',12);
		$pdf->Cell('','3','');
		$pdf->SetXY(25,70);
		$pdf->Cell('','','Hall Ticket No :','','','');
		$pdf->SetXY(75,70);
		$pdf->Cell('','',$appno,'','','');
		
		$name="";
		$profileimage = "";
		$paymenttype = "";
		$testcenter = "";
		$slotno = "";
		$email = "";
		if ($stmt = $mysqli->prepare("SELECT full_name, image_url, email, paymentType, center FROM gatApplicationsView where gatAppNo = ?")) { 
			$stmt->bind_param('s', $appno); 
			$stmt->execute();
			$stmt->store_result();
			$stmt->bind_result($name,$profileimage,$email,$paymenttype,$testcenter); 
			$stmt->fetch();
		}
		$pdf->SetFont('times','B',12);
		$pdf->Cell('','3','');
		$pdf->SetXY(25,80);
		$pdf->Cell('','','Name of the Candidate :','','','');
		$pdf->SetXY(75,80);
		$pdf->Cell('','',$name,'','','');
		$pdf->SetFont('times','B',12);
		$pdf->Cell('','3','');
		$pdf->SetXY(25,90);
		$pdf->Cell('','','Payment Type :','','','');
		$pdf->SetXY(75,90);
		$pdf->Cell('','',$paymenttype,'','','');
		$upload_path = dirname(dirname(__FILE__)).'/authentication/profile_images/';
		$image = $upload_path.$profileimage;
		$pdf->Image($image,'160','55','35','45');		
		$pdf->Image('../authentication/images/table.jpg','28','110','165');
		$pdf->SetFont('times','B',12);			
		$pdf->SetXY(75,120);
		$pdf->Cell('20','','Venue','','','C');
		$pdf->SetXY(157,118);
		$pdf->Cell('20','','Time & Date','','','C');
		$pdf->SetXY(157,122);
		$pdf->Cell('20','','of the Test','','','C');
		if($testcenter=='Hyderabad')
		{
			$pdf->SetFont('times','B',10);
			$pdf->SetXY(32,132);
			$pdf->Cell('20','','G Narayanamma Institute of Technology & Science,');
			$pdf->SetXY(32,137);
			$pdf->Cell('20','','Shaikpet, Mehdipatnam, Hyderabad-500008');	
			$pdf->SetXY(32,147);
			$pdf->Cell('20','','Contact: Col MS Raju');	
			$pdf->SetXY(32,152);
			$pdf->Cell('20','','Phone: 9949159160, 040-23565648');
		}
		$pdf->SetXY(158,140);
		$pdf->Cell('20','',$timingslot,'','','C');
		$pdf->SetXY(158,134);
		$pdf->Cell('20','',$date_of_exam,'','','C');
		$pdf->SetFont('times','B',14);
		$pdf->Cell('','3','');
		$pdf->SetXY(25,165);
		$pdf->Cell('','','Instructions for Candidates:','','','');
		$pdf->SetFont('times','B',10);
		$pdf->Cell('','3','');
		$pdf->SetXY(30,173);
		$pdf->Cell('','','1. Any error/change in your name/address must be communicated immediately through','','','');
		$pdf->Cell('','3','');
		$pdf->SetXY(30,178);
		$pdf->Cell('','','email to : enquiries2016@msitprogram.net.','','','');
		$pdf->Cell('','3','');
		$pdf->SetXY(30,183);
		$pdf->Cell('','','2. The candidate is being conditionally allowed to appear in the entrance examination','','','');
		$pdf->Cell('','3','');
		$pdf->SetXY(30,188);
		$pdf->Cell('','','without verifying whether he/she satisfies the eligibility criterion. This will be examined','','','');
		$pdf->Cell('','3','');
		$pdf->SetXY(30,193);
		$pdf->Cell('','','at the time of final admission, if granted.','','','');
		$pdf->Cell('','3','');
		$pdf->SetXY(40,220);
		$pdf->Cell('','','Signature of the Candidate','','','');
		$pdf->Cell('','3','');
		$pdf->SetXY(150,220);
		$pdf->Cell('','','(Dean, CIHL)','','','');
		$pdf->Image('../authentication/images/sign.jpg','138','205','40');
		$pdf->Output($pdffilename,'I');
		$pdf->Close();
?>